swagger: "2.0"
info:
    description: "API that describes and serves all of the HTTP status codes"
    version: "v1"
    title: "CrowzFX HTTP Status Codes API"
consumes:
    - "application/json"
produces:
    - "application/json"
basePath: "/api/http-status/v1"
schemes:
    - "https"
    - "http"

paths:
    /all:
        get:
            operationId: "handler.return_all_codes"
            tags:
                - "All Codes"
            summary: "GET All HTTP codes"
            description: "Read all of the HTTP stored status codes"
            responses:
                200:
                    description: "Successful status fetch operation"
                    schema:
                        type: "array"
                        items:
                            $ref: "#/definitions/StatusCode"
    /code/{code}:
        get:
            operationId: "handler.return_one_code"
            tags:
                - "A Status Code"
            summary: "GET a specific HTTP code"
            description: "Read a specific status code"
            parameters:
            - name: "code"
              in: "path"
              description: "The HTTP status code to lookup"
              type: "integer"
              required: true
            responses:
                200:
                    description: "Successful status fetch operation"
                    schema:
                        $ref: "#/definitions/StatusCode"

definitions:
    StatusCode:
        type: "object"
        properties:
            code:
                type: "integer"
            name:
                type: "string"
            description:
                type: "string"
    ErrorResponse:
        type: "object"
        properties:
            error:
                type: "string"
            description: 
                type: "string"